### ISSUE TITLE
Weights support

### ISSUE THREAD

**Issue by iamfullofspam** [lmjohns3/theanets#71] opened 2015-03-11 21:05 UTC
Hi, thanks for the library, I enjoyed playing with it.
But in physics application we often have weights for training samples...

Is it possible to add this feature to theanets as third optional argument in tuple?
exp.train((X, y, sample_weight))

One way is to add weights as multiplier in loss function, the other way is use weights in drawing batches (events with greater weight will be drawn to batch with greater probability). 

Is it possible for theanets?

**Comment by lmjohns3** [comment] 2015-03-24 22:23
I'm going to close this as a duplicate of #58

**Closed by lmjohns3** 2015-03-24 22:23 UTC
